in0_blinding = ""
in0_idx = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
in0_owner = ""
in0_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
in0_sk = ""
in0_token = ""
in0_value = ""
in1_blinding = ""
in1_idx = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
in1_owner = ""
in1_path = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
in1_sk = ""
in1_token = ""
in1_value = ""
membership_root = ""
nullifier0 = ""
nullifier1 = ""
out0_blinding = ""
out0_owner = ""
out0_token = ""
out0_value = ""
out1_blinding = ""
out1_owner = ""
out1_token = ""
out1_value = ""
out_commitment0 = ""
out_commitment1 = ""
public_fee = ""
public_recipient = ""
public_value = ""
relayer = ""
token = ""
