/**
 * HonkVerifier integration tests.
 *
 * Validates two critical properties of the bb 0.84.0-generated UltraHonk verifier
 * deployed on Robinhood Chain (0xAEa82dbA04e11F7455DF1D19344AD49026f69a83):
 *
 *  1. A valid proof produced by the browser-side bb.js 0.82.0 prover (keccak mode)
 *     is accepted by the on-chain verifier.
 *
 *  2. A forged / randomly altered proof is rejected.
 *
 * The proof fixture below was generated offline with:
 *   - @noir-lang/noir_js@1.0.0-beta.6   (circuit execution → witness)
 *   - @aztec/bb.js@0.82.0               (UltraHonkBackend, keccak: true)
 * against circuits/transfer/target/viona_transfer.json.
 *
 * The witness encodes a self-spend:
 *   in0: note(owner=1, token=1, value=100, blinding=2), sk=3, at tree index 0
 *   in1: zero-value padding note(owner=0,token=0,value=0,blinding=0), at tree index 1
 *   out0: note(owner=1, token=1, value=100, blinding=4)
 *   out1: zero-value padding
 *   public_value = public_fee = public_recipient = relayer = 0
 *
 * Run: cd contracts && npx hardhat test
 */

import { ethers } from "hardhat";
import assert from "assert";
import fixtureData from "./fixtures/transfer_proof.hex.json";

// ── Proof fixture (bb.js 0.82.0, keccak mode) ────────────────────────────────
// Generated by scripts/gen-proof-fixture.cjs; re-run to refresh if circuit changes.

const FIXTURE = {
  // Public inputs in circuit declaration order (10 values).
  publicInputs: [
    "0x25b83be86790e194d0e1f4e01b8a4c8d0e343ac89e13e2c4dc71f43b592b1bdf", // membership_root
    "0x05419d626dc3df8166148773e60caa672f4ddc731de3655f656940f9e8f6cd5a", // nullifier0
    "0x23834d6f9c07f4262d1655cdcf302e406aa25e64a90b216ed3163f10f40f4e9d", // nullifier1
    "0x12e70d0c98962640edfa58724253a50506f1cd478eb5defedff948b58f6e326b", // out_commitment0
    "0x2cdc2ec26d67d6cb1b656ebbed40f597c6b69958c9415d1982ab5187a1ac3020", // out_commitment1
    "0x0000000000000000000000000000000000000000000000000000000000000001", // token
    "0x0000000000000000000000000000000000000000000000000000000000000000", // public_value
    "0x0000000000000000000000000000000000000000000000000000000000000000", // public_fee
    "0x0000000000000000000000000000000000000000000000000000000000000000", // public_recipient
    "0x0000000000000000000000000000000000000000000000000000000000000000", // relayer
  ] as const,

  // UltraHonk proof bytes (bb.js 0.82.0, keccak Fiat-Shamir), 14080 bytes.
  // The proof does NOT include the public inputs (split format).
  proof: fixtureData.proof as string,
};

// ── Helpers ───────────────────────────────────────────────────────────────────

async function deployVerifier() {
  const factory = await ethers.getContractFactory("HonkVerifier");
  const v = await factory.deploy();
  await v.waitForDeployment();
  return v as unknown as {
    verify(proof: Uint8Array | string, pub: string[]): Promise<boolean>;
    getAddress(): Promise<string>;
  };
}

/** Corrupt a random byte inside the proof. */
function corruptProof(hexProof: string): string {
  const bytes = Buffer.from(hexProof.slice(2), "hex");
  // Flip a byte in the middle of the proof (avoid header/trailer)
  const idx = Math.floor(bytes.length / 2);
  bytes[idx] = (bytes[idx]! ^ 0xff) & 0xff;
  return "0x" + bytes.toString("hex");
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("HonkVerifier (bb 0.84.0 UltraHonk)", function () {
  this.timeout(120_000); // proof-heavy — allow generous time

  let verifierAddr: string;

  before(async function () {
    const v = await deployVerifier();
    verifierAddr = await v.getAddress();
    console.log("  HonkVerifier deployed at:", verifierAddr);
  });

  // ── Helpers ───────────────────────────────────────────────────────────────
  //
  // The bb 0.84.0 UltraHonk verifier reverts with custom errors (SumcheckFailed,
  // ShpleminiFailed, …) rather than returning false for invalid proofs.
  // This helper catches any revert and treats it as a rejection.

  async function expectRejected(
    fn: () => Promise<boolean>,
    label: string,
  ): Promise<void> {
    let reverted = false;
    let returnedFalse = false;
    try {
      const result = await fn();
      returnedFalse = result === false;
    } catch {
      reverted = true;
    }
    assert.ok(
      reverted || returnedFalse,
      `${label}: expected revert or false but call succeeded with true`,
    );
    console.log(`  ${label} ✅`);
  }

  // ── Test 1: forged proof is rejected ─────────────────────────────────────
  it("rejects a random 14080-byte forged proof", async function () {
    const v = await deployVerifier();
    const forged = "0x" + "ab".repeat(14080);
    await expectRejected(
      () => v.verify(forged, [...FIXTURE.publicInputs]),
      "Forged proof rejected",
    );
  });

  // ── Test 2: altered valid proof is rejected ───────────────────────────────
  it("rejects a bitflipped valid proof", async function () {
    const v = await deployVerifier();
    await expectRejected(
      () => v.verify(corruptProof(FIXTURE.proof), [...FIXTURE.publicInputs]),
      "Bitflipped proof rejected",
    );
  });

  // ── Test 3: wrong public inputs reject a valid proof ─────────────────────
  it("rejects a valid proof with tampered public inputs", async function () {
    const v = await deployVerifier();
    const wrongPub = [...FIXTURE.publicInputs] as string[];
    wrongPub[0] = "0x" + "dead".repeat(16); // corrupt membership_root
    await expectRejected(
      () => v.verify(FIXTURE.proof, wrongPub),
      "Tampered public inputs rejected",
    );
  });

  // ── Test 4: valid bb.js 0.82.0 proof accepted by bb 0.84.0 verifier ──────
  it("accepts a valid proof from the bb.js 0.82.0 prover (keccak mode)", async function () {
    const v = await deployVerifier();

    const accepted = await v.verify(FIXTURE.proof, [...FIXTURE.publicInputs]);
    assert.strictEqual(
      accepted,
      true,
      [
        "Valid proof rejected — possible causes:",
        "  1. Proof uses poseidon challenges instead of keccak (set keccak:true in UltraHonkBackend)",
        "  2. bb.js 0.82.0 / bb 0.84.0 proof format incompatibility",
        "  3. Fixture is stale — re-run scripts/gen-proof-fixture.cjs",
      ].join("\n")
    );
    console.log("  Valid proof accepted ✅ (bb.js 0.82.0 → bb 0.84.0 compatible)");
  });
});
