/**
 * ShieldedPool.spend — pool-level end-to-end integration test.
 *
 * Verifies that a valid UltraHonk proof produced by the browser-side bb.js 0.82.0
 * prover (keccak mode) passes through ShieldedPool.spend end-to-end:
 *   - pool.knownRoot(membershipRoot) accepts the root derived from the circuit witness
 *   - nullifiers are recorded as spent after a successful spend()
 *   - output commitments are emitted via NoteCommitted events
 *   - a forged proof is rejected by the real HonkVerifier (not the always-true StubVerifier)
 *   - shield() still succeeds with StubVerifier as shieldVerifier
 *
 * Setup:
 *   Uses TestShieldedPool (inherits ShieldedPool + exposes insertLeafForTest) to seed the
 *   tree with the exact note commitments used when the fixture proof was generated, including
 *   the zero-value padding note (value=0) that cannot be inserted via production shield().
 *
 * Proof fixture (generated by scripts/gen-proof-fixture.cjs, bb.js 0.82.0, keccak mode):
 *   in0  = note(owner=1, token=1, value=100, blinding=2) at tree index 0
 *   in1  = note(owner=0, token=0, value=0,   blinding=0) at tree index 1  (zero padding)
 *   out0 = note(owner=1, token=1, value=100, blinding=4)
 *   out1 = note(owner=0, token=0, value=0,   blinding=5)  (distinct from in1 → no DuplicateCommitment)
 *   public_value = public_fee = public_recipient = relayer = 0
 *
 * Run: cd contracts && npx hardhat test
 */

import { ethers } from "hardhat";
import assert from "assert";
import fixtureData from "./fixtures/transfer_proof.hex.json";

// ── Proof fixture ─────────────────────────────────────────────────────────────
const PROOF_HEX    = fixtureData.proof as string;
const MEMBER_ROOT  = "0x25b83be86790e194d0e1f4e01b8a4c8d0e343ac89e13e2c4dc71f43b592b1bdf";
const NULLIFIER_0  = "0x05419d626dc3df8166148773e60caa672f4ddc731de3655f656940f9e8f6cd5a";
const NULLIFIER_1  = "0x23834d6f9c07f4262d1655cdcf302e406aa25e64a90b216ed3163f10f40f4e9d";
const OUT_COMMIT_0 = "0x12e70d0c98962640edfa58724253a50506f1cd478eb5defedff948b58f6e326b";
const OUT_COMMIT_1 = "0x2cdc2ec26d67d6cb1b656ebbed40f597c6b69958c9415d1982ab5187a1ac3020";
// Input note commitments: poseidon2Hash([owner,token,value,blinding])
const IN_COMMIT_0  = "0x06f20cd465e5fc6c1157db90f85103302f86b1e9b9924585e707c08191148c4b"; // hash4(1,1,100,2)
const IN_COMMIT_1  = "0x20be000d93b852c82d4e02c94e9e61fa3a0e79949aac3af4010620651d416134"; // hash4(0,0,0,0)

const DUMMY_CIPHER = "0x" + "aa".repeat(64);
const STUB_PROOF   = "0x" + "00".repeat(64); // accepted by StubVerifier

// ── Pool deployment ───────────────────────────────────────────────────────────

async function deployTestPool() {
  const HonkFactory = await ethers.getContractFactory("HonkVerifier");
  const honk        = await HonkFactory.deploy();
  await honk.waitForDeployment();

  const StubFactory = await ethers.getContractFactory("StubVerifier");
  const stub        = await StubFactory.deploy();
  await stub.waitForDeployment();

  const TestPoolFactory = await ethers.getContractFactory("TestShieldedPool");
  const pool = await TestPoolFactory.deploy(
    await honk.getAddress(),
    await stub.getAddress(),
  );
  await pool.waitForDeployment();

  return { pool, honk, stub };
}

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("ShieldedPool.spend (pool integration)", function () {
  this.timeout(300_000);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let pool: any;
  let honkAddr: string;
  let stubAddr: string;

  before(async function () {
    const deployed = await deployTestPool();
    pool     = deployed.pool;
    honkAddr = await deployed.honk.getAddress();
    stubAddr = await deployed.stub.getAddress();
    console.log("  TestShieldedPool:", await pool.getAddress());
    console.log("  spendVerifier (HonkVerifier):", honkAddr);
    console.log("  shieldVerifier (StubVerifier):", stubAddr);
  });

  // ── Test 1: verifier slots correctly assigned ─────────────────────────────
  it("spendVerifier is HonkVerifier; shieldVerifier is StubVerifier", async function () {
    assert.strictEqual(await pool.spendVerifier(),  honkAddr, "spendVerifier should be HonkVerifier");
    assert.strictEqual(await pool.shieldVerifier(), stubAddr, "shieldVerifier should be StubVerifier");
    console.log("  Verifier assignments correct ✅");
  });

  // ── Test 2: shield() works with StubVerifier ──────────────────────────────
  it("shield() accepts any proof via StubVerifier (deposits operational)", async function () {
    const tx = await pool.shield(
      0n, 100n, IN_COMMIT_0, ethers.ZeroHash, DUMMY_CIPHER, STUB_PROOF, { value: 100n },
    );
    await tx.wait();
    assert.equal(await pool.nextLeafIndex(), 1, "Tree should have 1 leaf");
    console.log("  shield() with StubVerifier accepted ✅");
  });

  // ── Test 3: forged spend proof rejected ───────────────────────────────────
  it("rejects a forged spend() proof — HonkVerifier, not StubVerifier, guards spend()", async function () {
    // Seed tree: insert IN_COMMIT_1 (zero-value padding) via test bypass
    await (await pool.insertLeafForTest(IN_COMMIT_1)).wait();

    const poolRoot = await pool.root();
    assert.strictEqual(poolRoot, MEMBER_ROOT, "Pool root must match fixture membershipRoot");

    const FORGED = "0x" + "cc".repeat(14080);
    let reverted = false;
    try {
      await pool.spend(
        {
          membershipRoot: poolRoot,
          nullifiers:     [NULLIFIER_0, NULLIFIER_1],
          commitments:    [OUT_COMMIT_0, OUT_COMMIT_1],
          newRoot:        ethers.ZeroHash,
          token:          0n, value: 0n, fee: 0n,
          recipient:      ethers.ZeroAddress,
          relayer:        ethers.ZeroAddress,
        },
        [DUMMY_CIPHER, DUMMY_CIPHER],
        FORGED,
      );
    } catch {
      reverted = true;
    }
    assert.ok(reverted, "Forged proof should be rejected by HonkVerifier");
    console.log("  Forged spend proof rejected by HonkVerifier ✅");
  });

  // ── Test 4: valid bb.js 0.82.0 proof accepted end-to-end ─────────────────
  it("accepts a valid bb.js 0.82.0 proof through ShieldedPool.spend (end-to-end)", async function () {
    // State: IN_COMMIT_0 at index 0, IN_COMMIT_1 at index 1 (from tests 2 and 3).
    // The fixture proof was built over this exact tree.
    const poolRoot = await pool.root();
    assert.strictEqual(
      poolRoot, MEMBER_ROOT,
      `Pool root mismatch — expected ${MEMBER_ROOT}, got ${poolRoot}`,
    );

    // token=1n matches the circuit's public input (proof was generated with token=1).
    // value=0 → no token transfer attempted.
    const spendStmt = {
      membershipRoot: MEMBER_ROOT,
      nullifiers:     [NULLIFIER_0, NULLIFIER_1],
      commitments:    [OUT_COMMIT_0, OUT_COMMIT_1],
      newRoot:        ethers.ZeroHash,
      token:          1n, value: 0n, fee: 0n,
      recipient:      ethers.ZeroAddress,
      relayer:        ethers.ZeroAddress,
    };

    const tx      = await pool.spend(spendStmt, [DUMMY_CIPHER, DUMMY_CIPHER], PROOF_HEX);
    const receipt = await tx.wait();
    console.log("  spend() gas used:", receipt?.gasUsed?.toString());

    // Nullifiers must be spent
    assert.ok(await pool.nullifierSpent(NULLIFIER_0), "nullifier0 must be spent");
    assert.ok(await pool.nullifierSpent(NULLIFIER_1), "nullifier1 must be spent");
    console.log("  Nullifiers marked spent ✅");

    // Output commitments must be emitted
    const topic = ethers.id("NoteCommitted(uint32,bytes32,bytes)");
    const notes  = (receipt?.logs ?? []).filter(
      (l: { topics: string[] }) => l.topics[0] === topic,
    );
    assert.ok(notes.length > 0, "spend() must emit NoteCommitted for output notes");
    console.log("  NoteCommitted emitted for", notes.length, "output note(s) ✅");

    // Nullifier replay must revert
    let replayed = false;
    try {
      await pool.spend(spendStmt, [DUMMY_CIPHER, DUMMY_CIPHER], PROOF_HEX);
    } catch {
      replayed = true;
    }
    assert.ok(replayed, "Nullifier replay should revert");
    console.log("  Nullifier replay rejected ✅");

    console.log("\n  ✅ End-to-end: bb.js 0.82.0 → ShieldedPool.spend → state changes confirmed");
  });
});
