// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

/**
 * @title IVerifier
 * @notice Minimal interface for a UltraHonk ZK verifier generated by Barretenberg bb.
 *
 * The VIONA Shield pool calls verify() before accepting any spend().
 * The implementation is swapped out once VIONA's Noir circuits are compiled.
 */
interface IVerifier {
    /**
     * @param proof      The UltraHonk proof bytes produced by the client-side prover.
     * @param publicInputs  ABI-encoded public inputs (in circuit declaration order).
     * @return True if the proof is valid for the given public inputs.
     */
    function verify(bytes calldata proof, bytes32[] calldata publicInputs)
        external view returns (bool);
}
